# GitHub Pages configuration
plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
  
include:
  - currys/
  - boux-avenue/
  - adnoc/
  
# Site settings
title: "LLM Competitive Analysis Dashboard"
description: "Multi-client dashboard for analyzing brand presence in LLM responses"